WB\QbankBundle\Entity\ClassificationRelResources:
    type: entity
    table: classification_rel_resources
    repositoryClass: WB\QbankBundle\Entity\ClassificationRelResourcesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        weight:
            type: integer
    manyToOne:
        resourceId:
            type: integer
            column: resource_id
            targetEntity: Resources
            inversedBy: classificationRelResources
            joinColumn:
                name: resource_id
                referencedColumnName: id
                onDelete: CASCADE
        classificationId:
            type: integer
            column: classification_id
            targetEntity: Classifications
            inversedBy: classificationRelResources
            joinColumn:
                name: classification_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
