WB\QbankBundle\Entity\IndicatorRelSources:
    type: entity
    table: indicator_rel_sources
    repositoryClass: WB\QbankBundle\Entity\IndicatorRelSourcesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        weight:
            type: integer
            nullable: TRUE
            
    manyToOne:
        resourceId:
            type: integer
            column: resource_id
            targetEntity: Resources
            inversedBy: indicatorRelSources
            joinColumn:
                name: resource_id
                referencedColumnName: id
                onDelete: CASCADE
        indId:
            type: integer
            column: ind_id
            targetEntity: Indicators
            inversedBy: indicatorRelSources
            joinColumn:
                name: ind_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
