WB\QbankBundle\Entity\IndicatorRelModules:
    type: entity
    table: indicator_rel_modules
    repositoryClass: WB\QbankBundle\Entity\IndicatorRelModulesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        weight:
            type: integer
            nullable: TRUE
    manyToOne:
            moduleId:
                type: integer
                column: module_id
                targetEntity: QuestionnaireModules
                inversedBy: indicatorRelModules
                joinColumn:
                    name: module_id
                    referencedColumnName: id
                    onDelete: CASCADE
            indId:
                type: integer
                column: ind_id
                targetEntity: Indicators
                inversedBy: indicatorRelModules
                joinColumn:
                    name: ind_id
                    referencedColumnName: id
                    onDelete: CASCADE
    lifecycleCallbacks: {  }
