WB\QbankBundle\Entity\IndicatorRelClassifications:
    type: entity
    table: indicator_rel_classifications
    repositoryClass: WB\QbankBundle\Entity\IndicatorRelClassificationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        weight:
            type: integer
            nullable: TRUE
    manyToOne:
                classificationId:
                    type: integer
                    column: classification_id
                    targetEntity: Classifications
                    inversedBy: indicatorRelClassifications
                    joinColumn:
                        name: classification_id
                        referencedColumnName: id
                        onDelete: CASCADE
                indId:
                    type: integer
                    column: ind_id
                    targetEntity: Indicators
                    inversedBy: indicatorRelClassifications
                    joinColumn:
                        name: ind_id
                        referencedColumnName: id
                        onDelete: CASCADE
    lifecycleCallbacks: {  }
