<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationsRepository extends EntityRepository
{
    public function countClassifications()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(c.id)
                FROM WBQbankBundle:Classifications c'
            );

        return $query->getSingleScalarResult();
    }

    public function searchClassifications($classified, $published, $keyword, $excludedIds, $sort = 'ASC')
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder();
        $query
            ->select('c')
            ->from('WBQbankBundle:Classifications', 'c')
            ->orderBy('c.name', $sort);

        if ($keyword) {
            $query
                ->leftJoin('c.classificationCodes', 'cc')
                ->where(
                    $query->expr()->orX(
                        $query->expr()->like('c.name', ':keyword'),
                        $query->expr()->like('c.description', ':keyword'),
                        $query->expr()->like('cc.label', ':keyword')
/*                        $query->expr()->like('cc.description', ':keyword'),
                        $query->expr()->like('cc.value', ':keyword')*/
                    )
                )
                ->setParameter('keyword', "%" . $keyword . "%");
        }

        if (false !== $classified) {
            $query
                ->leftJoin('c.classificationGrpRef', 'g')
                ->andWhere("g.id IS " . $classified);
        }

        if (false !== $published) {
            $query
                ->andWhere("c.published = :published")
                ->setParameter('published', $published);
        }

        if (!empty($excludedIds)) {
            $query
                ->andWhere($query->expr()->notIn('c.id', ':excludedIds'))
                ->setParameter('excludedIds', $excludedIds);
        }


        $q = $query->getQuery();
        return $q->getResult();
    }


}
