<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassificationGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationGroupsRepository extends EntityRepository
{
    public function countClassificationGroups()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(g.id)
                FROM WBQbankBundle:ClassificationGroups g'
            );

        return $query->getSingleScalarResult();
    }

}
