<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndGrpRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndGrpRefRepository extends EntityRepository
{
    public function getIndicatorsReferences($published, $keyword)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder();
        $query
            ->select('r')
            ->from('WBQbankBundle:IndGrpRef', 'r')
            ->join('r.indId', 'i')
            ->orderBy('r.weight', 'ASC');

        if ($keyword) {
            $query
                ->leftJoin('i.indicatorAlias', 'a')
                ->where(
                    $query->expr()->orX(
                        $query->expr()->like('i.name', ':keyword'),
                        $query->expr()->like('i.description', ':keyword'),
                        $query->expr()->like('a.name', ':keyword')
                    )
                )
                ->setParameter('keyword', "%" . $keyword . "%");
        }

        if ($published) {
            $query
                ->andWhere("i.published = 1");
        }

        $q = $query->getQuery();
        return $q->getResult();
    }
}
