<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicatorGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicatorGroupsRepository extends EntityRepository
{
    public function countIndicatorGroups()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(g.id)
                FROM WBQbankBundle:IndicatorGroups g'
            );

        return $query->getSingleScalarResult();
    }

    public function searchIndicatorGroups($keyword){
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT i
                FROM WBQbankBundle:IndicatorGroups i
                WHERE i.name LIKE :keyword
                OR i.description LIKE :keyword
                ORDER BY i.name ASC'
            )->setParameter('keyword', '%' . $keyword . '%');

        return $query->getResult();
    }


}
