<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicatorRelResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicatorRelResourcesRepository extends EntityRepository
{
    /* not tested
    //remove references to classifications from questions by classification id
    public function updateWeight($resource_id, $ind_id, $weight)
    {
        $qb = $this->createQueryBuilder("IndicatorRelResources");
        $qb->update('WBQbankBundle:IndicatorRelResources', 'q');
        $qb->set('q.weight',':weight');
        $qb->setParameter('weight',$weight);
        $qb->where("q.resourceId =:resource_id");
        $qb->setParameter('resource_id', $resource_id);
        $qb->where("q.indicatorId =:ind_id");
        $qb->setParameter('ind_id', $ind_id);
        
        //echo $qb->getQuery()->getSql();

        $qb->getQuery()->execute();     
        return $qb;
    }*/
}
