<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationsRepository extends EntityRepository
{
    public function searchOrganizations($published, $keyword, $excludedIds)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder();
        $query
            ->select('o')
            ->from('WBQbankBundle:Organizations', 'o')
            ->orderBy('o.name', 'ASC');

        if ($keyword) {
            $query
                ->where(
                    $query->expr()->orX(
                        $query->expr()->like('o.name', ':keyword'),
                        $query->expr()->like('o.description', ':keyword'),
                        $query->expr()->like('o.nickName',':keyword')
                    )
                )
                ->setParameter('keyword', "%" . $keyword . "%");
        }

        if (false !== $published) {
            $query
                ->andWhere("o.published = :published")
                ->setParameter('published', $published);
        }

        if (!empty($excludedIds)) {
            $query
                ->andWhere($query->expr()->notIn('o.id', ':excludedIds'))
                ->setParameter('excludedIds', $excludedIds);
        }


        $q = $query->getQuery();
        return $q->getResult();
    }


}
