<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireModulesRelResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireModulesRelResourcesRepository extends EntityRepository
{
    
    //removes multiple resources
    //@resources array()
    public function batchRemoveResources($quest_module_id,$resources)
    {
        $isDeleted = $this->createQueryBuilder("QuestionnaireModulesRelResources")
            ->delete()
            ->where('QuestionnaireModulesRelResources.resourceId NOT IN (:id)')->setParameter("id", $resources)
            ->andWhere('QuestionnaireModulesRelResources.questModuleId = :quest_module_id')->setParameter("quest_module_id", $quest_module_id)
            ->getQuery()->execute();

        return $isDeleted;
    }


}
