<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireModulesRelSourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireModulesRelSourcesRepository extends EntityRepository
{
    //removes multiple resources
    //@resources array()
    public function batchRemoveSources($quest_module_id,$resources)
    {
        $isDeleted = $this->createQueryBuilder("QuestionnaireModulesRelSources")
            ->delete()
            ->where('QuestionnaireModulesRelSources.resourceId NOT IN (:id)')->setParameter("id", $resources)
            ->andWhere('QuestionnaireModulesRelSources.questModuleId = :quest_module_id')->setParameter("quest_module_id", $quest_module_id)
            ->getQuery()->execute();

        return $isDeleted;
    }
}
