<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireGroupsRepository extends EntityRepository
{
    public function countQuestionnaireGroups()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(g.id)
                FROM WBQbankBundle:QuestionnaireGroups g'
            );
            
        return $query->getSingleScalarResult();
    }

}
