<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRelClassificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRelClassificationsRepository extends EntityRepository
{
    public static function getSkipValue(EntityManager $em,$classification_code_id,$question_id) {
        $sql = "SELECT skip_value FROM questions_rel_classifications c where c.question_id = " .
            $question_id . " and c.classification_code_id = " . $classification_code_id;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        $skipValue = $stmt->fetchAll();
        return $skipValue[0]["skip_value"];
    }
}
