<?php

namespace WB\QbankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermGrpRefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermGrpRefRepository extends EntityRepository
{
    public function getConceptsReferences($published, $keyword)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder();
        $query
            ->select('r')
            ->from('WBQbankBundle:TermGrpRef', 'r')
            ->join('r.termId', 't')
            ->orderBy('r.weight', 'ASC');

        if ($keyword) {
            $query
                ->where(
                    $query->expr()->orX(
                        $query->expr()->like('t.name', ':keyword'),
                        $query->expr()->like('t.description', ':keyword')
                    )
                )
                ->setParameter('keyword', "%" . $keyword . "%");
        }

        if ($published) {
            $query
                ->andWhere("t.published = 1");
        }

        $q = $query->getQuery();
        return $q->getResult();
    }

}
